using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Banner.Generator;

[Generator]
public class BannerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<BannerOptions> options =
            context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
            {
                provider.GlobalOptions.TryGetValue("build_property.BannerText", out var text);
                provider.GlobalOptions.TryGetValue("build_property.BannerFont", out var font);
                provider.GlobalOptions.TryGetValue("build_property.BannerColor", out var fontColor);
                provider.GlobalOptions.TryGetValue("build_property.BannerAlignment", out var alignment);
                provider.GlobalOptions.TryGetValue("build_property.BannerLineSpacing", out var lineSpacing);
                provider.GlobalOptions.TryGetValue("build_property.PoweredBy", out var poweredBy);
                provider.GlobalOptions.TryGetValue("build_property.AutoPrint", out var autoPrint);

                return new BannerOptions(
                    string.IsNullOrWhiteSpace(text) ? "Banner" : text!,
                    string.IsNullOrWhiteSpace(font) ? "standard" : font!,
                    string.IsNullOrWhiteSpace(fontColor) ? "default" : fontColor!,
                    string.IsNullOrWhiteSpace(alignment) ? "left" : alignment!,
                    LineSpacing: int.TryParse(lineSpacing, out var spacing) ? spacing : 1,
                    !bool.TryParse(poweredBy, out var on) || on,
                    bool.TryParse(autoPrint, out var auto) && auto
                );
            });

        context.RegisterSourceOutput(options, static (spc, opts) =>
        {
            using var fontStream = FontCatalog.Open(opts.Font);
            if (fontStream is null)
            {
                spc.ReportDiagnostic(Diagnostics.UnknownFontDiagnostic(opts.Font));
                return;
            }

            var fontColor = ResolvedColor.Parse(opts.FontColor);
            if (fontColor is null)
            {
                spc.ReportDiagnostic(Diagnostics.UnknownFontColorDiagnostic(opts.FontColor));
                return;
            }

            if (!Enum.TryParse<Alignment>(opts.Alignment, ignoreCase: true, out var alignment)
                || !Enum.IsDefined(typeof(Alignment), alignment))
            {
                spc.ReportDiagnostic(Diagnostics.UnknownAlignmentDiagnostic(opts.Alignment));
                return;
            }

            var rendered = BannerRenderer.RenderBanner(fontStream, opts.Text, fontColor, alignment, opts.LineSpacing);

            var plain = SymbolDisplay.FormatLiteral(rendered.Plain, quote: true);
            var colored = SymbolDisplay.FormatLiteral(rendered.Colored, quote: true);
            var poweredBy = SymbolDisplay.FormatPrimitive(opts.PoweredBy, quoteStrings: false, useHexadecimalNumbers: false);
            var autoPrintCall = opts.AutoPrint
                ? "global::Banner.BannerRuntime.PrintBanner();"
                : string.Empty;

            spc.AddSource("BannerText.g.cs", $$"""
                                               // <auto-generated/>
                                               #nullable enable

                                               namespace Banner.Generated;

                                               internal static class BannerModuleInit
                                               {
                                                   private const string Plain = {{plain}};
                                                   private const string Colored = {{colored}};

                                                   [global::System.Runtime.CompilerServices.ModuleInitializer]
                                                   internal static void Init() 
                                                   {
                                                       global::Banner.BannerRuntime.Register(Plain, Colored, {{poweredBy}});
                                                       {{autoPrintCall}}
                                                   }
                                               }
                                               """);
        });
    }
}